"Important Key Mapping
let mapleader = ','
inoremap <leader>s <C-c>:w<cr>
inoremap <leader>w <C-c>:w<cr>
inoremap <leader>wq <C-c>:wq<cr>
nnoremap <leader>s :w<cr>
nnoremap <leader>w :w<cr>
nnoremap <leader>q :q<cr>
nnoremap <leader>wq :wq<cr>
nnoremap <leader>copy :%w !pbcopy<cr>
nnoremap <leader>k gcc
nnoremap <leader>, :b 
nnoremap <leader>. :bd<cr>

"General
set number
set relativenumber
set backspace=2
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set nocompatible
set ignorecase
set smartcase

"Backup
set backup
set backupdir=~/.dotfiles/vim/sys/backup
set directory=~/.dotfiles/vim/sys/tmp

"Split Screen Controls
nnoremap <leader>sv :vsplit<cr>
nnoremap <leader>sh :split<cr>
noremap <C-l> <C-w>l
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k

"Pathogen
execute pathogen#infect()
syntax on 
filetype plugin indent on

function CheckForTemplate()
    let extension = expand('%:e')
    let skelfile = $DOTFILES . "/vim/templates/skel." . extension
    if filereadable(skelfile)
        execute "0read " . fnameescape(skelfile)
    else
        echom "could not load " . "." . extension . " template"
    endif
endf

if has("autocmd")
    autocmd BufNewFile * call CheckForTemplate()
endif
